learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('learning_logs.urls')),
    path('users/', include('users.urls', namespace='users')),
    # homepage
]

learning_logs/urls.py
"""
URL patterns for learning_logs
"""

from django.urls import path
from . import views

app_name = 'learning_logs'
urlpatterns = [
    path('', views.index, name='index'),
    # homepage
    path('topics/', views.topics, name='topics'),
    # topics page
    path('topics/<int:topic_id>/', views.topic, name='topic'),
    # page for each topic
    path('new_topic/', views.new_topic, name='new_topic'),
    # page for adding new topics
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
    # path for adding new entry
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
    # path for editing entry
    path('del_entry/<int:entry_id>/', views.del_entry, name='del_entry'),
    # path for deleting entry
    path('del_topic/<int:topic_id>/', views.del_topic, name='del_topic'),
    # path for deleting topics
    path('confirm_topic_del/<int:topic_id>/', views.confirm_del_topic, name='confirm_del_topic'),
    # path for confirming deleting topics
    path('confirm_entry_del/<int:entry_id>/', views.confirm_del_entry, name='confirm_del_entry'),
    # path for confirming deleting entries
]
# app name and urls

users/urls.py
"""
URL patterns for users application
"""

from django.urls import path, include
from . import views

app_name = 'users'

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    # default auth urls
    path('register/', views.register, name='register')
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Topic(models.Model):
    """
    Class for Topic that user is learning about
    """

    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    # initialize fields

    def __str__(self):
        return self.text

class Entry(models.Model):
    """
    Class for user entries
    """

    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    # initialize fields

    class Meta:
        # metadata for an entry
        verbose_name_plural = 'entries'

    def __str__(self):
        return f'{self.text[:50]}...'

learning_logs/forms.py
"""
Forms file for Learning Log
"""

from django import forms
from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    """
    Form for topic
    """

    class Meta:
        """
        Metadata for TopicForm
        """

        model = Topic
        fields = ['text']
        labels = {'text': ''}

class EntryForm(forms.ModelForm):
    """
    Class for the form to create a new entry
    """

    class Meta:
        """
        Metadata for entry form
        """

        model = Entry
        fields = ['text']
        labels = {'text': 'Entry:'}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

learning_logs/views.py
from django.shortcuts import render, redirect
from .models import Topic, Entry
from .forms import TopicForm, EntryForm
from django.contrib.auth.decorators import login_required
from django.http import Http404

# Create your views here.

def index(request):
    """
    Homepage for learning log
    """

    return render(request, 'learning_logs/index.html')

@login_required
def topics(request):
    """
    Topics page
    """

    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    # define topics and context for the page

    return render(request, 'learning_logs/topics.html', context)

@login_required
def topic(request, topic_id):
    """
    Individual topic page
    """

    topic = Topic.objects.get(id=topic_id)
    if topic.owner != request.user:
        raise Http404
    # make sure topic's owner is the one who requested it

    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    # define topic, entries and context for webpage

    return render(request, 'learning_logs/topic.html', context)

@login_required
def new_topic(request):
    """
    Add new topic
    """

    if request.method != "POST":
        form = TopicForm()
        # if data not submitted, create blank form
    else:
        form = TopicForm(data=request.POST)
        # submit POST data

        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return redirect('learning_logs:topics')
            # if form is valid, save and redirect

    context = {'form': form}
    # create context and return new blank form

    return render(request, 'learning_logs/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
    """
    Create new entry
    """

    topic = Topic.objects.get(id=topic_id)

    if request.method != "POST":
        form = EntryForm()
    # create empty form if data is not submitted

    else:
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('learning_logs:topic', topic_id=topic_id)
        # if form is valid, save entry and redirect to topic page

    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    """
    Edit an entry
    """

    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    # obtain entry and topic

    if topic.owner != request.user:
        raise Http404
    # make sure entry's owner is the one who requested it

    if request.method != 'POST':
        form = EntryForm(instance=entry)
        # prefill the form with existing entry
    
    else:
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topic', topic_id=topic.id)
        # submit form and save and redirect

    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)

@login_required
def del_entry(request, entry_id):
    """
    Delete an entry
    """

    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    # obtain entry and topic

    if topic.owner == request.user:
        Entry.objects.get(id=entry_id).delete()
        return redirect('learning_logs:topic', topic_id=topic.id)
    else:
        raise Http404
    # if user owns the topic, then delete the entry
    # and redirect, else raise 404 error

@login_required
def del_topic(request, topic_id):
    """
    Delete a topic
    """

    topic = Topic.objects.get(id=topic_id)
    # obtain topic

    if topic.owner == request.user:
        Topic.objects.get(id=topic_id).delete()
        return redirect('learning_logs:topics')
    else:
        raise Http404
    # if user owns the topic, then delete the topic
    # and redirect, else raist 404 error

@login_required
def confirm_del_topic(request, topic_id):
    """
    Confirm to delete a topic
    """

    topic = Topic.objects.get(id=topic_id)
    # obtain topic

    if topic.owner == request.user:
        context={'topic_id': topic_id}
        return render(request, 'learning_logs/confirm_del_topic.html', context)
    else:
        raise Http404
    # if user owns the topic, then delete the topic
    # and redirect, else raist 404 error

@login_required
def confirm_del_entry(request, entry_id):
    """
    Confirm to delete a entry
    """

    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    # obtain entry

    if topic.owner == request.user:
        context={'entry_id': entry_id, 'topic_id': topic.id}
        return render(request, 'learning_logs/confirm_del_entry.html', context)
    else:
        raise Http404
    # if user owns the topic, then delete the topic
    # and redirect, else raist 404 error

learning_logs/templates/learning_logs/base.html
{% load bootstrap4 %}

<!doctype html>
<html lang='en'>

    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width-device-width, initial-scale=1, shrink-to-fit=no">
        <title>Learning Log</title>

        {% bootstrap_css %}
        {% bootstrap_javascript jquery='full' %}
    </head>

    <body>
        <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
            <a class="navbar-brand" href="{% url 'learning_logs:index' %}">
                Learning Log
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse"
            data-target="#navbarCollapse" aria-controls="navbarCollapse"
            aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                    <a class="nav-link" href="{% url 'learning_logs:topics'%}">
                    Topics</a></li>
                </ul>
                <ul class="navbar-nav ml-auto">
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                        <span class="navbar-text">Welcome, {{ user.username }}.</span>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:register' %}">Register</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:login' %}">Log in</a></li>
                    {% endif %}
                </ul>
            </div>
        </nav>

        <main role="main" class="container">
            <div class="pb-2 mb-2 border-bottom">
                {% block page_header %}{% endblock page_header %}
            </div>
            <div>
                {% block content %}{% endblock content %}
            </div>
        </main>
    </body>

</html>

learning_logs/templates/learning_logs/confirm_del_entry.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap4 %}

{% block page_header %}
    <h3>
        Are you sure you want to delete this entry?
    </h3>
{% endblock page_header %}

{% block content %}
{% buttons %}
<a class="btn btn-danger btn-lg" href="{% url 'learning_logs:del_entry' entry_id %}" role="button">
    Delete
</a>
<a class="btn btn-default btn-lg" href="{% url 'learning_logs:topic' topic_id %}" role="button">
    Cancel
</a>
{% endbuttons %}
{% endblock content %}

learning_logs/templates/learning_logs/confirm_del_topic.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap4 %}

{% block page_header %}
    <h3>
        Are you sure you want to delete this topic?
    </h3>
{% endblock page_header %}

{% block content %}
{% buttons %}
<a class="btn btn-danger btn-lg" href="{% url 'learning_logs:del_topic' topic_id %}" role="button">
    Delete
</a>
<a class="btn btn-default btn-lg" href="{% url 'learning_logs:topics' %}" role="button">
    Cancel
</a>
{% endbuttons %}
{% endblock content %}

learning_logs/templates/learning_logs/edit_entry.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap4 %}
{% block page_header %}
    <h2>
        Edit entry in <a href="{% url 'learning_logs:topic' topic.id %}">
            {{ topic }}
        </a>
    </h2>
    {% endblock page_header %}

    {% block content %}

    <form class="form" action="{% url 'learning_logs:edit_entry' entry.id %}" method='post'>
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
        <button name='submit' class="btn btn-primary">Save changes</button>
        {% endbuttons %}
    </form>

{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends 'learning_logs/base.html' %}

{% block page_header %}
    <div class="jumbotron">
        <h1 class="display-3">Organize how you learn.</h1>
        <p class="lead">Learning Log helps you keep track of what you learn. You can organize your learning into different topics, and those topics can have their own multiple entries. Just start learning a topic, and whenever you learn something new about it, make an entry for it in your Learning Log!</p>
        {% if user.is_authenticated %}
            <a class="btn btn-lg btn-primary" href="{% url 'learning_logs:topics' %}"
          role="button">My topics</a>
        {% else %}
            <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}"
            role="button">Register</a>
        {% endif %}
    </div>
{% endblock page_header %}

learning_logs/templates/learning_logs/new_entry.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap4 %}

{% block page_header %}
    <h3>Add a new entry</h3>
{% endblock page_header %}

{% block content %}
<form action="{% url 'learning_logs:new_entry' topic.id %}" method = 'post'>
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button class="btn btn-primary" name='submit'>
        Add entry
    </button>
    {% endbuttons %}
</form>

{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap4 %}

{% block page_header %}
    <h2>
        Add a new topic
    </h2>
{% endblock page_header %}

{% block content %}

<form method='post' action="{% url 'learning_logs:new_topic' %}" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button name="submit" class="btn btn-primary">Add topic</button>
        {% endbuttons %}
    </form>

{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}

{% block page_header %}
    <h3>{{ topic }}</h3>
{% endblock page_header %}

{% block content %}

    <h3 style="float: right;">
        <a href="{% url 'learning_logs:new_entry' topic.id %}">
            Add new entry
        </a>
    </h3>
<br>
<br>
<br>
        {% for entry in entries %}
        <div class="card mb-3">
            
            <h4 class="card-header">
                {{ entry.date_added|date:'M d, Y H:i' }}
                <div  style="float:right;">
                <small>
                    <a href="{% url 'learning_logs:edit_entry' entry.id %}">
                        edit entry
                    </a>   
                </small>
                <small>
                    <a href="{% url 'learning_logs:confirm_del_entry' entry.id %}">
                        delete entry
                    </a>
                </small>
                </div>
            </h4>
            <div class="card-body">
                {{ entry.text|linebreaks }}
            </div>
        </div>
        {% empty %}
            <p>
                There are no entries for this topic yet.
            </p>
        {% endfor %}
{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends 'learning_logs/base.html' %}

{% block page_header %}
    <h1>Topics</h1>
{% endblock page_header %}

{% block content %}

    <ul>
        {% for topic in topics %}
            <li><h2>
                <a href="{% url 'learning_logs:topic' topic.id %}">
                    {{ topic }}
                </a>
                <small>
                    <a href="{% url 'learning_logs:confirm_del_topic' topic.id %}">
                        delete topic
                    </a>
                </small>
            </h2></li>
        {% empty %}
            <li><h3>No topics have been added yet.</h3></li>
        {% endfor %}
    </ul>
    <h3><a href="{% url 'learning_logs:new_topic' %}">Add a new topic</a></h3>

{% endblock content %}